#! /bin/sh -e
set -x
PREREQ=""

prereqs () {
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions



#copy_exec /bin/tar /bin/
#copy_exec /sbin/mkfs.ext4 /sbin/
#copy_exec /bin/gzip /sbin/
copy_exec /usr/bin/awk /bin/
copy_exec /usr/bin/tr /bin/
copy_exec /bin/grep /bin/
copy_exec /usr/bin/base64 /bin/
copy_exec /bin/sed /bin/
copy_exec /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /lib/x86_64-linux-gnu/
copy_exec /usr/lib/x86_64-linux-gnu/libxml2.so.2 /lib/x86_64-linux-gnu/
#copy_exec /usr/bin/openssl /bin/
#copy_exec /usr/lib/ssl/openssl.cnf /usr/lib/ssl/openssl.cnf
copy_exec /usr/bin/sha1sum /bin/sha1sum
copy_exec /usr/bin/sha256sum /bin/sha256sum
#copy_exec /sbin/cryptsetup /sbin/
#copy_exec /lib/modules/`uname -r`/kernel/drivers/md/dm-crypt.ko /lib/modules/`uname -r`/kernel/drivers/md/dm-crypt.ko

copy_exec $TBOOTXM_BIN/tpmextend /bin/
copy_exec $TBOOTXM_LIB/rpmmio.ko /lib/modules/`uname -r`/kernel/drivers/char/tpm/
copy_exec $TBOOTXM_BIN/verifier /bin/

exit 0
